### ISSUE TITLE
getContentItemMatrix should be static

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/page-bundle#25]
https://github.com/zicht/page-bundle/blob/109606a0acb6fb6e6e6a1b0151ebaad7a2dd31a3/src/Zicht/Bundle/PageBundle/Entity/Page.php#L46

this method should be static because its evaluated in static fashion to build up the cache for url generation.
In some cases people tend to use if statements. which causes bugs.

**Comment by 7ochem** [comment]
Won't do. There are use cases where different content items should be put into the matrix depending on a property of the entity. Also it's very easy to do `(new FooPage())->getContentItemMatrix()` to get the matrix when not having an actual object available.
