### ISSUE TITLE
Contentitems translation inside the dropdown is not found

### ISSUE THREAD

**Issue by wpbenner** [zicht/page-bundle#39]
For some reason you now need 2 different types of translation when creating a content-item. 

This one is used after you have selected a content-item
``` 
content_item:
    type:
        call_to_action: Call To Action 
```
![screenshot from 2018-08-23 16-59-45](https://user-images.githubusercontent.com/7580635/44533505-f4428a80-a6f5-11e8-8ccb-488eb74ee74c.png)

And this one is used before selecting a content-item

``` 
content_item:
    type:
         zicht_bundle_zicht_site_bundle_entity_content_item_call_to_action: Call To Action
```

If you dont have the above way of translating the content-item the screenshot below will hapen. 

![screenshot from 2018-08-23 16-39-25](https://user-images.githubusercontent.com/7580635/44532340-31594d80-a6f3-11e8-87e9-f73bfe826bdb.png)

So you have a duplicate translation this way in a sence. I dont really know if this is a desired way of translating content-items.

**Comment by 7ochem** [comment]
I also noticed this and these translation strings are built in two different places:

- [src/Zicht/Bundle/PageBundle/Type/ContentItemTypeType.php](https://github.com/zicht/page-bundle/blob/release/5.x/src/Zicht/Bundle/PageBundle/Type/ContentItemTypeType.php#L119)
  Uses: `Str::humanize(Str::classname($subject->getConvertToType()))`
  which is filtered further in the template ([src/Zicht/Bundle/PageBundle/Resources/views/form_theme.html.twig](https://github.com/zicht/page-bundle/blob/release/5.x/src/Zicht/Bundle/PageBundle/Resources/views/form_theme.html.twig#L5-L7)):
  `'content_item.type.' ~ (type|replace({' ': '_'})|lower)`
- [src/Zicht/Bundle/PageBundle/Type/DiscriminatorMapType.php](https://github.com/zicht/page-bundle/blob/release/5.x/src/Zicht/Bundle/PageBundle/Type/DiscriminatorMapType.php#L47)
  Uses: `'content_item.type.' . strtolower(str_replace(' ', '_', Str::humanize($className)))`

Both come down to the same conversions, except the one starts with the **class name** and the other with the **fully qualified class name**.

Maybe the content item itself should provide a method for the type _"code"_ (snake cased humanized class name or FQCN).
