### ISSUE TITLE
Composer.json is missing dependencies

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/page-bundle#7]
the zicht/admin-bundle and zicht/url-bundle are missing in the require part.

**Comment by drm** [comment]
Because they aren't required. Read the tutorial ;)

**Comment by muhammedeminakbulut** [comment]
`https://github.com/zicht/page-bundle/search?utf8=%E2%9C%93&q=UrlBundle&type= ` @drm these use's cause the tests to fail actually.
